#!/bin/bash

echo ""
echo "> Formatting committed C files"

# Getting all diffed .c files from commit
COMMITED_FILES_STR=$(git diff --cached --name-only | grep \\.c)

# Splitting given string by enter and storing in an array
readarray -t COMMITED_FILES_ARR_TMP <<<"$COMMITED_FILES_STR"

COMMITED_FILES_ARR=()

# Remove empty strings
for element in "${COMMITED_FILES_ARR_TMP[@]}"; do
    if [ -n "$element" ]; then
        COMMITED_FILES_ARR+=("$element")
    fi
done

# Formatting files from an array
if [ ${#COMMITED_FILES_ARR[@]} -gt 0 ]; then
    for file in "${COMMITED_FILES_ARR[@]}"; do
        clang-format -i $file
        git add $file
    done
    echo "> C files formatted"
else
    echo "> No C files found"
fi

echo ""
